routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return redirect()->route('dashboard'); });
Route::group(['middleware' => ['web', 'auth']], function () {
    
    Route::get('dashboard', 'DashboardController')->name('dashboard');
    
    Route::post('ajax_select/{type}', 'AjaxSelectController')->name('ajaxSelect');

	Route::get('user/all', 'UserController@all')->name('user.all');
    Route::resource('user', 'UserController')->except('create', 'edit', 'show');
	
    Route::get('client/all', 'ClientController@all')->name('client.all');
    Route::resource('client', 'ClientController')
        ->parameters(['client' => 'client'])->except('create', 'edit', 'show');
	
    Route::get('region/all', 'RegionController@all')->name('region.all');
    Route::resource('region', 'RegionController')
        ->parameters(['region' => 'region'])->except('create', 'edit', 'show');
	
    Route::get('group/all', 'GroupController@all')->name('group.all');
    Route::resource('group', 'GroupController')
        ->parameters(['group' => 'group'])->except('create', 'edit', 'show');
	
    Route::post('merchant/all', 'MerchantController@all')->name('merchant.all');
    Route::resource('merchant', 'MerchantController')
        ->parameters(['merchant' => 'merchant'])->except('create', 'edit', 'show');
	
    Route::post('merchantOutlet/all', 'MerchantOutletController@all')->name('merchantOutlet.all');
    Route::resource('merchantOutlet', 'MerchantOutletController')
        ->parameters(['merchantOutlet' => 'merchantOutlet'])->except('create', 'edit', 'show');
	

});

Auth::routes([
    'register'  => true,
    'verify'    => false,
    'reset'     => false,
    'confirm'   => false,
]);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];
    // protected $fillable = [
    //     'username', 'email', 'password',
    // ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Requests\UserRequest;
use DB;

class UserController extends Controller
{
    public function all(Request $request)
    {
        abort_if(!$request->header('X-XSRF-TOKEN'), 404);
        return User::get();
    }

    public function index()
    {
        return view('contents.user.index');
    }
    
    public function store(UserRequest $request)
    {
        User::create($request->validated());
        return true;
    }

    public function update(UserRequest $request, User $user)
    {
        $user->update($request->validated());
        return true;
    }

    public function destroy(User $user)
    {
        $user->delete();
        return true;
    }
}

resources/views/contents/user/index.blade.php
@extends('layouts.template', ['activeMenu' => 'user'])

@section('breadcrumb')
<div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
	<div class="d-flex">
		<div class="breadcrumb">
			<a href="{{ route('dashboard') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
			<span class="breadcrumb-item">User Management</span>
			<span class="breadcrumb-item active">User</span>
		</div>
	</div>
</div>
@endsection

@section('content')
<!-- Basic datatable -->
<div class="card">
	<div class="card-header header-elements-inline">
        <h5 class="card-title">List User</h5>
        <div class="header-elements">
            <button type="button" @click="createModal" class="btn bg-teal-400 btn-labeled btn-labeled-left rounded-round"><b><i class="icon-plus-circle2"></i></b> Add Data</button>
        </div>
	</div>

	<table class="table table-hover table-striped table-xs text-nowrap" id="datatable_basic">
		<thead>
			<tr>
				<th>#</th>
                <th>Username</th>
                <th>Email</th>
                <th class="text-center">Actions</th>
			</tr>
		</thead>
		<tbody>
			<tr v-if="mainData" v-for="item, index in mainData" :key="index">
				<td v-text="index+1"></td>
                <td v-text="item.username"></td>
                <td v-text="item.email"></td>
                <td style="width: 16px;">
                    <div class="btn-group">
                        <button type="button" class="btn btn-outline bg-primary-400 text-primary-400 btn-icon btn-sm rounded-round ml-2"
                            data-popup="tooltip" title="" data-placement="left" data-original-title="Edit" @click="editModal(item)">
                            <i class="fas fa-pencil-alt"></i></button>
                        <button type="button" class="btn btn-outline bg-danger-400 text-danger-400 btn-icon btn-sm rounded-round ml-2"
                            data-popup="tooltip" title="" data-placement="left" data-original-title="Delete" @click="deleteData(item.id)">
                            <i class="far fa-trash-alt"></i></button>
                    </div>
                </td>
			</tr>
		</tbody>
	</table>
</div>
<!-- /basic datatable -->

<!-- Basic modal -->
<div id="modal_default" class="modal fade" tabindex="-1">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header" :class="editMode ? 'bg-primary' : 'bg-teal'">
                <h4 class="modal-title">@{{ (editMode ? 'Edit ' : 'New ')+toastMessage }}</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>

			<form @submit.prevent="editMode ? updateData() : storeData()" @keydown="form.onKeydown($event)">
				<div class="modal-body">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input id="username" type="text" placeholder="Input Nama User" class="form-control"
                            v-model="form.username" :class="{ 'is-invalid': form.errors.has('username') }">
                            <has-error :form="form" field="username"></has-error>
                    </div>

                    <div class="form-group">
                        <label for="email">Email</label>
                        <input id="email" type="email" placeholder="Input Email" class="form-control"
                            v-model="form.email" :class="{ 'is-invalid': form.errors.has('email') }">
                            <has-error :form="form" field="email"></has-error>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-6">
                            <label for="password">Password</label>
                            <input id="password" type="password" placeholder="Input Password" class="form-control"
                                v-model="form.password" :class="{ 'is-invalid': form.errors.has('password') }">
                                <has-error :form="form" field="password"></has-error>
                        </div>
                        <div class="col-md-6">
                            <label for="password_confirmation">Re-Type Password</label>
                            <input id="password_confirmation" type="password" placeholder="Input Ulang Password" class="form-control"
                                v-model="form.password_confirmation" :class="{ 'is-invalid': form.errors.has('password') }">
                                <has-error :form="form" field="password"></has-error>
                        </div>
                    </div>
				</div>

				<div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
					<button type="submit" class="btn" :class="editMode ? 'bg-primary' : 'bg-teal-600'">
						@{{ editMode ? 'Update' : 'Save' }}
					</button>
				</div>
			</form>
		</div>
	</div>
</div>
<!-- /basic modal -->
@endsection

@push('js')
<script>
    var app = new Vue({
        el: '#app',
        data: {
        	mainData: [],
            editMode : false,
            form : new Form({
                id: '',
                username: '',
                email: '',
                password: '',
                password_confirmation: '',
            }),
            toastMessage: 'User',
        },
        mounted() {
            $('.select-search').select2();
            $('.form-control-uniform').uniform();
	        $('#datatable_basic').DataTable();
	        this.refreshDatatable();
        },
        methods: {
            createModal(){
                this.editMode = false;
                this.form.reset();
                this.form.clear();
                $('#modal_default').modal('show');
            },
            editModal(data){
                this.editMode = true;
                this.form.fill(data)
                this.form.clear();
                $('#modal_default').modal('show');
            },
            vueChanged(){
                this.form.iddepartementoutlet = $('#outlet').val()
            },
            storeData(){
                this.form.post("{{ route('user.store') }}")
                    .then(response => {
                        $('#modal_default').modal('hide')
                        basicFormSuccess(this.toastMessage, 'created')
                        this.refreshDatatable()
                    })
                    .catch(e => {
                        basicFormError(e)
                    })
            },
            updateData(){
                url = "{{ route('user.update', ':id') }}".replace(':id', this.form.id)
                this.form.put(url)
                    .then(response => {
                        $('#modal_default').modal('hide');
                        basicFormSuccess(this.toastMessage, 'updated')
                        this.refreshDatatable()
                    })
                    .catch(e => {
                        basicFormError(e)
                    })
            },
            deleteData(id){
                DeleteConfirmation.fire().then((result) => {
                    if (result.value) {
                        url = "{{ route('user.destroy', ':id') }}".replace(':id', id)
                        this.form.delete(url)
                            .then(response => {
                                basicFormSuccess(this.toastMessage, 'deleted')
                                this.refreshDatatable()
                            })
                            .catch(e => {
                                basicFormError(e)
                            })
                    }
                })
            },
            refreshDatatable(){
            	axios.get("{{ route('user.all') }}")
                    .then(response => {
                        $('#datatable_basic').DataTable().destroy();
                        this.mainData = response.data
                        this.$nextTick(function() {
                            $('#datatable_basic').DataTable({
                                dom: '<"datatable-header "fBl><"datatable-scroll-wrap"t><"datatable-footer"ip>',
                                drawCallback: function(){
                                    $('[data-popup="tooltip"]').tooltip({trigger : 'hover'});
                                }
                            });
                            redrawTable();
                        })
                    })
                    .catch(e => {
                        basicFormError(e)
                    })
            }
        },
    })
</script>
@endpush